### ISSUE TITLE
Investigate localdb & docker compatibility

### ISSUE THREAD

**Issue by gianlazz** [leolazz/ToDoList#4]
Description:
"localdb" is the default database used when generating a new asp-dotnet mvc project. It should be investigated whether localdb will work in the available asp-dotnet-core linux based docker images.

Done When:
- A determination on if localdb is supported by linux docker containers is made
- If it is not supported then a ticket shall be made to implement support for a database that is supported by linux docker images

**Comment by leolazz** [comment]
Seemingly it is possible to use localDb in a docker image, but it has to based on a windows file. Long-term it seems better to spend the time learn how to use a database generally supported rather than utilizing localdb for this application.

issue have been moved to a new ticket
